name: harmonica
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip
  # Build
  - setuptools>=45
  - setuptools_scm>=6.2
  - wheel
  - twine
  # Run-time
  - numpy
  - pandas
  - numba
  - scipy
  - scikit-learn
  - pooch>=0.7.0
  - verde>=1.5.0
  - xarray
  # Testing requirements
  - pytest
  - pytest-cov
  - coverage
  - boule
  # Documentation requirements
  - sphinx==3.5.*
  - sphinx-book-theme==0.0.41
  - sphinx-gallery==0.8.*
  - pyproj
  - matplotlib
  - cartopy>=0.18
  # Code style checks and autoformat
  - black>=20.8b1
  - isort
  - flake8
  - flake8-bugbear
  - flake8-builtins
  - flake8-functions
  - flake8-mutable
  - flake8-rst-docstrings
  - flake8-simplify
  - pep8-naming
  - pip:
      # Install flake8-unused-arguments through pip
      # (not available through conda yet)
      - flake8-unused-arguments
